name: user-config
port: 8080

user_srv_info:
  host: 127.0.0.1
  port: 50051
  name: user_srv

jwt:
  key: stUL!$ViY3&Ce$JC2OVyN&w@^hqmipqV

consul_info:
  host: '10.211.55.10'
  port: 8500

redis_info:
  host: 10.211.55.10
  port: 6379
  password: 123456